  CREATE TABLE "TEST"."SHIPMENT_STATUS" 
   (	"SHIPMENT_ID" NUMBER NOT NULL ENABLE, 
	"STATUS_TYPE_CODE" CHAR(4) DEFAULT '0100' NOT NULL ENABLE, 
	"STATUS_TYPE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"STATUS_TIMESTAMP" DATE DEFAULT sysdate, 
	"SENDER" VARCHAR2(10) NOT NULL ENABLE, 
	"STATUS_LOCATION" VARCHAR2(5) NOT NULL ENABLE, 
	"TRANSPORT_TYPE" CHAR(1) DEFAULT 'S' NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "SHIP_STAT_IS_ACTIVE_CHK" CHECK (IS_ACTIVE in ('Y','N')) ENABLE, 
	 CONSTRAINT "SHIP_STAT_TRNS_TYP_CHK" CHECK (TRANSPORT_TYPE in ('S','A')) ENABLE, 
	 CONSTRAINT "SHIP_SHIP_STAT_FK" FOREIGN KEY ("SHIPMENT_ID")
	  REFERENCES "TEST"."SHIPMENT" ("SHIPMENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;